### ISSUE TITLE
Dashboard for Web Forms - Grid and Chart layout is not saved when when the layout is changed

### ISSUE THREAD

**Issue by vesnaveen** [DevExpress-Examples/aspxdashboard-how-to-create-a-custom-dashboard-item-extension-t509294#1]
I am using Devexpress V2.1.13 version. We are facing an issue when we save the dashboard while moving two charts in middle. I edit an existing dashboard but moving the detailed grid to the bottom and the two charts to the middle.  After saving under a new file name, I display it and the grid is back in the middle. I have made a video for this.

https://user-images.githubusercontent.com/12605452/126494699-b7865ce1-c852-4547-bbd3-fc27ea5d26d4.mp4

and my layout is 
[DashboardLayout.txt](https://github.com/DevExpress-Examples/aspxdashboard-how-to-create-a-custom-dashboard-item-extension-t509294/files/6855998/DashboardLayout.txt)

and my save function same your code

**Comment by Stason4eg** [comment]
Hello,

Thank you for your layout. It looks correct to me.

I also noticed that you asked the same question [here](https://github.com/DevExpress-Examples/aspxdashboard-how-to-load-and-save-dashboards-from-to-a-database-t386418/issues/1).
I invite you to ask it in our Support Center - [https://devexpress.com/ask](https://devexpress.com/ask) and share your project with us so that we can research it and find a precise solution.
